export interface Organizacion {
  estado: string
  name: string
  tipo: string
  tags: string
  phones: string[]
  web?: string
  addres?: string
}
export const directorio: Organizacion[] = [
  {
    estado: "Nacional",
    name: "Alianza Nacional por el Derecho a decidir",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Interrupción legal del embarazo",
    phones: ["01 800 800 8821"],
    web: "https://andar.org.mx/puedes-elegir/#violencia",
  },
  {
    estado: "Nacional",
    name: "Comisión 1, 2, 3 por nosotras",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["N/D"],
    web: "https://docs.google.com/forms/d/e/1FAIpQLSdBfuGxJ99_1E-ZtiLwFOiUp3JaEzZWTUDZTxCGvNQleed08g/viewform",
    addres: "N/D",
  },
  {
    estado: "Nacional",
    name: "GIRE - Red Nacional por la Justicia Reproductiva",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Interrupción legal del embarazo",
    phones: ["01 (55) – 5658-6684."],
    web: "https://gire.org.mx/gire-quienes-somos/",
  },
  {
    estado: "Nacional",
    name: "Red por los derechos sexuales y reproductivos en México (ddeser)",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Interrupción legal del embarazo",
    phones: ["teacompanamos@ddeser.org"],
    web: "https://www.ddeser.org/",
  },
  {
    estado: "Nacional",
    name: "IPAS - México",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Interrupción legal del embarazo",
    phones: ["https://ipasmexico.org/contactanos/"],
    web: "https://ipasmexico.org/category/recursos/",
  },
  {
    estado: "Nacional",
    name: 'Centro de Apoyo a la Mujer"Margarita Magón"',
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["55 19 58 45"],
    web: "https://www.facebook.com/pages/category/Organization/Centro-De-Apoyo-a-La-Mujer-CAM-Margarita-Mag%C3%B3n-AC-1470777906532540/",
  },
  {
    estado: "Nacional",
    name: "Vereda Themis",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["(55) 5341 6570 / (55) 5396 5586 /53422767"],
    web: "http://www.veredathemis.org.mx/",
  },
  {
    estado: "Nacional",
    name: "Pro Ayuda a la Mujer Fundación Origen",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal, atención médica",
    phones: ["01800-015161755 20 44 21 y 0115"],
    web: "https://www.origenac.org/",
  },
  {
    estado: "Nacional",
    name: "Red Nacional de Refugios",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, refugios",
    phones: ["Tel: (55) 52436432Tel. 018008224460"],
    web: "https://www.rednacionalderefugiosorg.mx/",
  },
  {
    estado: "Nacional",
    name: "VICTIMATEL",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["5575 5461"],
  },
  {
    estado: "Nacional",
    name: "Línea SAPTEL.",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica ",
    phones: ["(55) 5259-8121."],
    web: "http://www.saptel.org.mx/que_es.html",
  },
  {
    estado: "Nacional",
    name: "Línea Mujeres de la Secretaría de las Mujeres",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica",
    phones: ["Teléfono: (55) 5658-1111 (opción 3)"],
    web: "http: //locatel.cdmx.gob.mx/mujeres/",
  },
  {
    estado: "Nacional",
    name: "Centros de Justicia para las Mujeres",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: [null],
    web: "https://www.gob.mx/cms/uploads/attachment/file/469801/Directorio_Centros_de_Justicia_para_las_Mujeres_2019.pdf",
  },
  {
    estado: "Nacional",
    name: "Comisiones Estatales de Derechos Humanos",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas, asesoría legal",
    phones: [null],
    web: "https://www.gob.mx/cms/uploads/attachment/file/394589/Directorio_Comisiones_Derechos_Humanos_2018.pdf",
  },
  {
    estado: "Nacional",
    name: "Líneas Telefónicas e Institutos Estatales de Atención a la Violencia contra las Mujeres",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: [null],
    web: "https://www.gob.mx/cms/uploads/attachment/file/394591/Directorio_Institutos_Estatales_y_Lineas_2018.pdf",
  },
  {
    estado: "Nacional",
    name: "Fiscalías Generales de Justicia",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a denuncias",
    phones: [null],
    web: "https://www.gob.mx/cms/uploads/attachment/file/395910/Directorio_Procuraduri_as-Fiscali_as_2018.pdf",
  },
  {
    estado: "Aguascalientes",
    name: "MUJER CONTEMPORANEA, A. C.",
    tipo: "Sociedad Civil",
    tags: "atención psicológica, asesoría legal",
    phones: ["449-918-81-76", "449-918-17-52"],
    addres: "ZARAGOZA NO. 601 COL. CENTRO, CP 20000, AGUASCALIENTES",
  },
  {
    estado: "Aguascalientes",
    name: "Comisión Estatal de Derechos Humanos de Aguascalientes",
    tipo: "Organismo gubernamental",
    tags: "atención a quejas",
    phones: ["449 140 78 70", "449 140 78 46", "449 140 78 60"],
    web: "http://www.dhags.org/",
    addres:
      "República de Perú No. 502, Fraccionamiento Santa Elena, C.P. 20271, Aguascalientes, Aguascalientes",
  },
  {
    estado: "Aguascalientes",
    name: "Instituto Aguascalentense de las Mujeres",
    tipo: "Organismo gubernamental",
    tags: "asesoría legal, atención psicológica, atienden infancias",
    phones: ["449 910 2580", "(449) 910 21 28 ext. 1370"],
    web: "http://www.aguascalientes.gob.mx/IAM/",
    addres: "V. Manuel Gómez Morín s/n Col. Ferronales , C.P. 20180",
  },
  {
    estado: "Baja California",
    name: "INMUJER Baja California",
    tipo: "Organismo gubernamental",
    tags: "atención psicológica, asesoría legal",
    phones: [
      "Mexicali: 686 558 6364 y 686 557 5495",
      "Tijuana: 664 608 0888",
      " Ensenada: 646 248 0873 y 646 248 0862",
    ],
    web: "http://www.bajacalifornia.gob.mx/inmujer/",
    addres:
      "Miguel Negrete, No. 1711, Col. Nueva, Mexicali, Baja California, C.P. 21000",
  },
  {
    estado: "Baja California",
    name: "Procuraduría de los Derechos Humanos y Protección Ciudadana del estado de Baja California",
    tipo: "Organismo gubernamental",
    tags: "atención a quejas",
    phones: ["664 973-2373 al 77 Lada Nacional", "Sin Costo: 800 026 7342"],
    web: "http://www.derechoshumanosbc.org/",
    addres:
      "Av. José Gorostiza N° 1151 entre Vía Rápida Oriente y Paseo Centenario, atrás de CANACO",
  },
  {
    estado: "Baja California Sur",
    name: "Comisión Estatal de Derechos Humanos de Baja California Sur",
    tipo: "Organismo gubernamental",
    tags: "atención a quejas",
    phones: [
      "612 123 14 04",
      "612 123 14 04",
      "612 123 23 32",
      "Lada Nacional Sin Costo: 800 690 83 00",
    ],
    web: "https://www.derechoshumanosbcs.org.mx/",
    addres:
      "Blvd. Constituyentes de 1975 e/ Calle Cabrilla y Calle Tiburón, Fraccionamiento Fidepaz, C. P. 23090, La Paz, Baja California Sur",
  },
  {
    estado: "Campeche",
    name: "Comisión Estatal de Derechos Humanos de Campeche",
    tipo: "Organismo gubernamental",
    tags: "refugio,atención a quejas,atención psicológica,interrupción legal del embarazo,atención médica,atienden infancias,asesoría legal",
    phones: ["981 816 08 97"],
    web: "http://codhecam.org.mx/",
    addres:
      "Prolongación 59 No. 6, Col. Centro, C.P. 24000, Campeche, Campeche",
  },
  {
    estado: "Campeche",
    name: "Instituto de la Mujer de Campeche",
    tipo: "Organismo gubernamental",
    tags: "refugio,atención a quejas,atención psicológica,interrupción legal del embarazo,atención médica,atienden infancias,asesoría legal",
    phones: ["981 811 6086"],
    web: "http://imecam.gob.mx/",
    addres:
      "Av. Adolfo López Mateos No. 250 altos, Colonia San Román, Campeche, México, C.P. 24040.",
  },
  {
    estado: "Campeche",
    name: "Observatorio de Violencia Social y de Género A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio,atención a quejas,atención psicológica,interrupción legal del embarazo,atención médica,atienden infancias,asesoría legal",
    phones: ["981 816 8948"],
    web: "https://www.facebook.com/ObservatorioCampeche/",
    addres: "Calle 65 No. 53, entre 14 y 16, Centro, Campeche, Campeche",
  },
  {
    estado: "Coahuila",
    name: "Acompañantes Laguna - Ddeser",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Interrupción legal del embarazo",
    phones: ["871 408 4396 / 871 188 8694 / 871 164 4539 / 871188 8694"],
    web: "https://www.facebook.com/acompananteslaguna",
  },
  {
    estado: "Coahuila",
    name: "Centro de Apoyo Opciones Dignas A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, refugio, asesoría legal, atención medica y psicológica",
    phones: ["877 888 0789"],
    web: "http://www.opcionesdignas.org/index.html",
    addres:
      "Privada Ayuntamiento No. 625 D, Colonia Aeropuerto Acuña, Coahuila",
  },
  {
    estado: "Coahuila",
    name: "Comisión Estatal de Derechos Humanos del Estado de Coahuila",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, atención a quejas",
    phones: ["844 416 61 96 y 844 416 20 50"],
    web: "http://cdhec.org.mx/",
    addres:
      "Blvd. Venustiano Carranza No. 1623, Col. República Poniente, entre Chihuahua y Colima, C.P. 25280, Saltillo, Coahuila",
  },
  {
    estado: "Coahuila",
    name: "Instituto Coahuilense de las Mujeres",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, asesoría legal, atención psicológica",
    phones: ["844 698 1080"],
    web: "https://www.icmujeres.gob.mx/",
    addres:
      "Boulevard Coahuila, Av. Fundadores y Centenario de Torreón Col. El Toreo, Saltillo, Coahuila.",
  },
  {
    estado: "Coahuila",
    name: "Red de Mujeres de La Laguna",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, interrupción legal del embarazo",
    phones: [],
    web: "https://www.facebook.com/RedMujeresLaguna.LagunalibredeViolencia/",
  },
  {
    estado: "Coahuila",
    name: "Aborto Seguro",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, interrupción legal del embarazo",
    phones: [],
    web: "https://www.facebook.com/abortosegurocoahuila",
    addres: "Centro de Salud Abastos. Torreón, Coahuila",
  },
  {
    estado: "Colima",
    name: "Comisión Estatal de Derechos Humanos del Estado de Colima",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, atención a quejas",
    phones: [
      "312 31 2 29 94, 31 4 77 95, 31 4 90 84, 31 4 71 86, Lada sin costo 800 6 96 76 72, Emergencias las 24 hrs 312 155 13 33",
    ],
    web: "https://cdhcolima.org.mx/",
    addres: "Degollado No. 79, Col. Centro, C.P. 28000, Colima, Colima",
  },
  {
    estado: "Colima",
    name: "Instituto Colimense de las Mujeres",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, atención a quejas",
    phones: ["800 836 4077"],
    web: "https://www.col.gob.mx/institutodelasmujeres",
    addres:
      "Complejo Administrativo del Gobierno del Estado, Edificio A, Planta Baja, 3er anillo Periférico, General Marcelino García Barragán s/n, , Colonia el Diezmo, Colima, Colima, C.P. 28010",
  },
  {
    estado: "Chiapas",
    name: "Secretaría de Igualdad de Género de Chiapas (SEIGEN)",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: [
      "961 264 0639 y 961 264 0643 - Línea digital SEIGEN: 961 462 9340",
    ],
    web: "http://seigen.chiapas.gob.mx/paimef#contacto",
    addres:
      "Blvd. Andrés Serra Rojas, Esq. con Lib. Norte S/N Anexo 1B Torre Chiapas, Col. El Retiro. C.P. 29040, Tuxtla Gutiérrez, Chiapas",
  },
  {
    estado: "Chiapas",
    name: "Comisión Estatal de los Derechos Humanos",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: [
      "Conmutador: (961) 602 8980 (961) 602 8981 Lada sin costo: 800 55 28 242",
    ],
    web: "https://cedhchiapas.org/cedh/about-us/",
    addres:
      "Primera Avenida Sur Oriente S/N, Edificio Plaza, 3er y 4to piso, Barrio San Roque Colonia Centro C.P. 29000 Tuxtla Gutiérrez, Chiapas.",
  },
  {
    estado: "Chihuahua",
    name: "Comisión Estatal de Derechos Humanos de Chihuahua",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["614 201 29 90, 614 201 29 91 y 614 201 29 92"],
    web: "https://cedhchihuahua.org.mx/wp/",
    addres:
      "Décima y Mina No. 1,000, Col. Centro, C.P. 31000, Chihuahua, Chihuahua",
  },
  {
    estado: "Chihuahua",
    name: "Centro de Derechos Humanos de las Mujeres (Cedehm)",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["6141329104 y 6142550305"],
    web: "https://cedehm.org.mx/es/?fbclid=IwAR373MTYSrHSlcJ0AXNB3YFVuVMk8tYXCNKX81OmgBbfu1o1mulU6GEH7QM#",
    addres:
      "Av. Juárez 4107-B Col. Centro, Chihuahua, Chih., México, C.P. 31000",
  },
  {
    estado: "Chihuahua",
    name: "Instituto Chihuahuense de la Mujer",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["614 429 3505"],
    web: "http://www.institutochihuahuensedelasmujeres.gob.mx/",
    addres:
      "Calle 1° de Mayo No. 1802, Col. Pacífico, Chihuahua, Chihuahua C.P. 31320",
  },
  {
    estado: "Ciudad de México",
    name: "Abogadas de las Mujeres (Secretaría de las Mujeres CDMX)",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["56 58 1111"],
    web: "https://www.semujeres.cdmx.gob.mx/abogadas-de-las-mujeres",
    addres: "N/D",
  },
  {
    estado: "Ciudad de México",
    name: "ADIVAC, Asociación para el Desarrollo Integral de Personas Violadas, A. C",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, atención médica",
    phones: ["5682 7969 y 5547 8639"],
    web: "https://www.adivac.org/",
    addres:
      "Salvador Díaz Mirón No. 140, Santa María La Ribera, Cuauhtémoc, Ciudad de México",
  },
  {
    estado: "Ciudad de México",
    name: "Apis Fundación para la Equidad",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["55 5539 3917 y 55 5539 0826 y 57045048"],
    web: "https://www.facebook.com/pages/category/Non-Governmental-Organization--NGO-/APIS-Fundaci%C3%B3n-Para-La-Equidad-AC-180887362093303/",
    addres: "N/D",
  },
  {
    estado: "Ciudad de México",
    name: "Asociación de Mujeres Sobrevivientes de Abuso Sexual, MUSAS, A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica",
    phones: ["55 5578 9197 y 55 1998 4568"],
    web: "http://www.musas.org.mx/",
    addres:
      "Dr. Durán No. 4, Despacho 214, Col. Doctores, Esq. con Eje Central Lázaro Cárdenas, Ciudad de México",
  },
  {
    estado: "Ciudad de México",
    name: "Casa Fuente de Apoyo a Mujeres Niñas y Niños Víctimas de Violencia",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, atención médica, refugio",
    phones: ["55 5994 5993"],
    web: "https://www.facebook.com/casafuentedeapoyo/",
    addres:
      "Calle Piedra Prieta No. 4 – 1 Colonia La Cascada, entre Río Mixcoac y Roca, Álvaro Obregón, Ciudad de México, CP 01490",
  },
  {
    estado: "Ciudad de México",
    name: "Casa Gaviota",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["55 3096 5189"],
    web: "https://www.casagaviota.org/",
    addres: "N/D",
  },
  {
    estado: "Ciudad de México",
    name: "Comisión de Derechos Humanos de la Ciudad de México",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["55 5229 5600"],
    web: "https://cdhcm.org.mx/",
    addres:
      "Av. Universidad No. 1449, Col. Florida, Pueblo de Axotla, C.P. 01030. Alcaldía Álvaro Obregón, Ciudad de México",
  },
  {
    estado: "Ciudad de México",
    name: "Defensa Jurídica y Educación para Mujeres, Vereda Themis, S.C",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["55 53 41 65 70 y 55 53 96 55 86"],
    web: "http://www.veredathemis.org.mx/",
    addres:
      "Av. De los Maestros No. 91-A, int. 14, Col. Agricultura, Deleg. Miguel Hidalgo, Ciudad de México",
  },
  {
    estado: "Ciudad de México",
    name: "Fundación Diarq",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["01 800 836 88 80/ 52 02 78 66"],
    web: "http://www.fdiarq.org/",
    addres:
      "Ciudad de México, C. Vicente Beristain #22, Vista Alegre, Cuauhtémoc, 06870 Ciudad de México, CDMX",
  },
  {
    estado: "Ciudad de México",
    name: "Lunas",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, asesoría legal",
    phones: ["55 55122836 ext. 502."],
    web: "https://www.semujeres.cdmx.gob.mx/servicios/servicio/lunas",
  },
  {
    estado: "Ciudad de México",
    name: "Red de abogadas Violeta",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["52 3333028714 y 52 1 33 1011 5368"],
    web: "https://abogadasvioleta.com/servicios/",
  },
  {
    estado: "Ciudad de México",
    name: "Resilio Consultores S.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: [" inclusion@resilioconsultores.com.mx"],
    web: "https://resilioconsultores.com.mx/",
  },
  {
    estado: "Ciudad de México",
    name: "Secretaría de las Mujeres CDMX",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["5555122836"],
    web: "https://www.semujeres.cdmx.gob.mx/",
    addres:
      "Av. Morelos 20, Col. Centro, Cuauhtémoc C.P. 06000, Ciudad de México",
  },
  {
    estado: "Ciudad de México",
    name: "Línea mujeres",
    tipo: null,
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica",
    phones: ["56581111"],
  },
  {
    estado: "Durango",
    name: "Acompañantes Laguna - Ddeser",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Interrupción legal del embarazo",
    phones: ["871 408 4396 / 871 188 8694 / 871 164 4539 / 871188 8694"],
    web: "https://www.facebook.com/acompananteslaguna",
  },
  {
    estado: "Durango",
    name: "Acompañantes Laguna",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica, interrupción legal del embarazo",
    phones: ["871 408 4396 / 871 188 8694"],
    web: "https://www.facebook.com/acompananteslaguna",
  },
  {
    estado: "Durango",
    name: "Comisión de Derechos Humanos del Estado de Durango",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["618 130 19 74"],
    web: "https://cedh-durango.org.mx/wp/",
    addres:
      "Cerro Gordo No. 32 int. 13, Centro Comercial del Bosque, Fraccionamiento Lomas del Parque, C.P. 34100, Durango, Durango",
  },
  {
    estado: "Durango",
    name: "Instituto de la Mujer Duranguense",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["618 827 0906"],
    web: "http://iemujer.durango.gob.mx/",
    addres: "Zaragoza No.526 Sur, Zona Centro, Durango, Durango C.P. 34000",
  },
  {
    estado: "Estado de México",
    name: "Comisión de Derechos Humanos del Estado de México",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención a quejas",
    phones: ["Lada sin costo los 24 hrs 800 999 4000"],
    web: "https://www.codhem.org.mx/LocalUser/codhem.org/htm/index.asp",
    addres:
      "Av. Nicolás San Juan No. 113, Col. Ex Rancho Cuauhtémoc C.P. 50010, Toluca, México",
  },
  {
    estado: "Estado de México",
    name: "Consejo Estatal de la Mujer y Bienestar Social del Estado de México",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["800 108 4053"],
    web: "https://semujeres.edomex.gob.mx/",
    addres:
      "Av. José María Morelos y Pavón Pte. 809, Col. La Merced, Toluca, Estado de México",
  },
  {
    estado: "Estado de México",
    name: "Fundación Vive 100% Mujer",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, refugio",
    phones: ["(555) 822-2212"],
    web: "http://www.vivemujer.org/",
    addres:
      "Carretera Villa Nicolás Romero Nº 31, Casa 30 B, Boulevares de Atizapán, Atizapán de Zaragoza, Edo. de México",
  },
  {
    estado: "Guanajuato",
    name: "ADIVAC, Asociación para el Desarrollo Integral de Personas Violadas, A. C",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, atención médica",
    phones: ["5682 7969 y 5547 8639 y Gto:Tel (477) 2511847"],
    web: "https://www.adivac.org/",
    addres:
      "Salvador Díaz Mirón No. 140, Santa María La Ribera, Cuauhtémoc, Ciudad de México y Gto: Independencia 305San Juan de Dios37370 León, Gto",
  },
  {
    estado: "Guanajuato",
    name: "Casa de apoyo a la mujer A.C",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["477 780 4090"],
    web: "https://casadeapoyoalamujer.org.mx/quienes-somos/",
    addres:
      "Casa de Apoyo a la Mujer A.C.Egipto 1005, Los Angeles, 37258 León, Gto.",
  },
  {
    estado: "Guanajuato",
    name: "Instituto para las Mujeres Guanajuatenses",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, refugio",
    phones: ["473 733 5523, 473 733 3259 y 473 733 2903"],
    web: "https://imug.guanajuato.gob.mx/",
    addres:
      "Plazuela de Cata #1, Col. Mineral de Cata, C.P. 36010 Guanajuato, GTO.",
  },
  {
    estado: "Guanajuato",
    name: "Procuraduría de los Derechos Humanos del Estado de Guanajuato",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, atención a quejas",
    phones: ["477 770 08 45, 477 770 41 13, Lada sin costo 800 470 4400"],
    web: "https://www.derechoshumanosgto.org.mx/",
    addres:
      "Av. Guty Cárdenas # 1444, Fraccionamiento Puerta San Rafael, León, Guanajuato, CP 37480",
  },
  {
    estado: "Guerrero",
    name: "Centro de Derechos Humanos de la Montaña, Tlachinollan, A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["757 476 1220, 476 1200"],
    web: "https://www.tlachinollan.org/",
    addres: "Mina No. 77 Col. Centro, Tlapa, Guerrero, México",
  },
  {
    estado: "Guerrero",
    name: "Centro Regional de Defensa de DDHH José María Morelos y Pavón, A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["756 104 0745, 747 471 6587"],
    web: "https://www.facebook.com/Centro-de-Defensa-De-Los-Derechos-Humanos-Jose-Maria-Morelos-y-Pav%C3%B3n-1370753579735743/https://www.facebook.com/Centro-de-Defensa-De-Los-Derechos-Humanos-Jose-Maria-Morelos-y-Pav%C3%B3n-1370753579735743/",
    addres:
      "Calle Cuauhtémoc No. 26, Col. Los Ángeles, C.P. 41100, Chilapa de Álvarez, Guerrero",
  },
  {
    estado: "Guerrero",
    name: "Comisión de Derechos Humanos del Estado de Guerrero",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: [
      "747 494 2000, Lada sin costo 800 710 66 00, 800 716 26 98 y 800 710 66 18",
    ],
    web: "http://www.cdheg.org/",
    addres:
      "Edificio Morelos Av. Benito Juárez, esq. con Galo Soberon y Parra, sin número. C.P. 39000, Chilpancingo, Gro.",
  },
  {
    estado: "Guerrero",
    name: "Secretaría de la Mujer de Guerrero",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["747 471 9700"],
    web: "http://www.semujer.guerrero.gob.mx/",
    addres:
      "Boulevard René Juárez Cisneros No. 62, Ciudad de los Servicios, C.P 39075, Chilpancingo, Guerrero; México.",
  },
  {
    estado: "Hidalgo",
    name: "Comisión de Derechos Humanos del Estado de Hidalgo",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: [
      "771 71 87 144, 771 71 81 696, Lada sin costo 800 717 6596 y whats: 7713600270",
    ],
    web: "https://cdhhgo.org/home/",
    addres:
      "Av. Juárez s/n esquina José María Iglesias Colonia Centro Pachuca de Soto, C.P. 42000",
  },
  {
    estado: "Hidalgo",
    name: "Instituto Hidalguense de las Mujeres",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 502 2221"],
    web: "http://mujeres.hidalgo.gob.mx/",
    addres:
      "Parque Hidalgo No. 103, Piso 2, Col. Centro, Pachuca, Hidalgo, C.P. 42000",
  },
  {
    estado: "Jalisco",
    name: "Colectivo Latinoamericano Emma Goldman A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["331 709 3064"],
  },
  {
    estado: "Jalisco",
    name: "Colectivo Mujeres Puerto Vallarta",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["322 159 8110"],
  },
  {
    estado: "Jalisco",
    name: "Comisión Estatal de Derechos Humanos de Jalisco",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["333 669 11 01"],
    web: "http://cedhj.org.mx/",
    addres:
      "Pedro Moreno No. 1616, Col. Americana, C.P. 44160, Guadalajara, Jalisco.",
  },
  {
    estado: "Jalisco",
    name: "Clínica Jurídica Ignacio Ellacuría ITESO",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["33 3669 3434"],
    web: "https://iteso.mx/web/general/detalle?group_id=3310946",
    addres:
      "Periférico Sur Manuel Gómez Morín # 8585 C.P. 45604 Tlaquepaque, Jalisco, México",
  },
  {
    estado: "Jalisco",
    name: "Red de Mujeres del 05 Distrito Jalisco",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría Legal",
    phones: ["3221331981"],
  },
  {
    estado: "Michoacán",
    name: "Comisión Estatal de Derechos Humanos de Michoacán",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["443 11 33 500, Lada sin costo 800 6403 188"],
    web: "http://cedhmichoacan.org/",
    addres:
      "Fernando Montes de Oca No. 108, Colonia Chapultepec Norte Morelia, Michoacán C.P. 58260",
  },
  {
    estado: "Michoacán",
    name: "Secretaría de Igualdad Sustantiva y Desarrollo de las Mujeres de Michoacán",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["443 113 6700"],
    web: "https://mujer.michoacan.gob.mx/",
    addres: "Av. Lázaro Cárdenas No. 2440, Col. Chapultepec Sur, C.P. 58260,",
  },
  {
    estado: "Morelos",
    name: "Comisión de Derechos Humanos del Estado de Morelos",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["777 322 16 00 y 777 322 16 01"],
    web: "https://cdhmorelos.org.mx/",
    addres:
      "Hermenegildo Galeana No. 39, Col. Acapatzingo, C.P. 62440, Cuernavaca, Morelos",
  },
  {
    estado: "Morelos",
    name: "Instituto de la Mujer para el Estado de Morelos",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 911 1515, 7775386609"],
    web: "https://www.immorelos.org.mx/atencion",
    addres:
      "Boulevard Benito Juárez No. 82, Col. Las Palmas, Cuernavaca, Morelos, C.P. 62050.",
  },
  {
    estado: "Nayarit",
    name: "Comisión de Derechos Humanos para el Estado de Nayarit",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["311 212 57 66 y 311 213 89 86"],
    web: "http://www.cddhnayarit.org/en",
    addres: "Av. México No. 276 Nte, Col. Centro, 63000 Tepic, Nayarit",
  },
  {
    estado: "Nuevo León",
    name: "Alternativas Pacíficas",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, atención médica, refugio",
    phones: ["81 8372 9694"],
    web: "https://alternativaspacificas.org/",
    addres:
      "Ignacio Zaragoza No. 555, Col. Centro, Monterrey, Nuevo León, C.P. 64000",
  },
  {
    estado: "Nuevo León",
    name: "Ciudadanos en Apoyo a los Derechos Humanos (CADHAC)",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["81 8343 5058"],
    web: "https://cadhac.org/",
    addres: "Padre Mier No. 617, Centro, C.P. 64000, Monterrey, Nuevo León",
  },
  {
    estado: "Nuevo León",
    name: "Instituto Estatal de las Mujeres de Nuevo León",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 003 784 323"],
    web: "https://www.nl.gob.mx/mujeres",
  },
  {
    estado: "Nuevo León",
    name: "Voces de Mujeres en Acción, A.C.",
    tipo: "Sociedad civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, interrupción legal del embarazo",
    phones: ["81 8169 3671"],
    web: "https://www.vocesdemujeres.org",
    addres: "Vista Aurora 412, Col. Linda Vista, Guadalupe, N.L.",
  },
  {
    estado: "Oaxaca",
    name: "Comité de Defensa Integral de Derechos Humanos Gobidxha (Codigodh)",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["951 5160802"],
    web: "https://codigodh.org/",
    addres:
      "Oficina Oaxaca, Mártires de Tacubaya No. 205 int.8, Centro, C.P. 68000, Oaxaca",
  },
  {
    estado: "Oaxaca",
    name: "Consorcio Oaxaca A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["951 1328996"],
    web: "https://consorciooaxaca.org/",
    addres:
      "Pensamientos 104Col. Reforma, C.P. 68050Oaxaca de Juárez, Oaxaca, México",
  },
  {
    estado: "Oaxaca",
    name: "Defensoría de Derechos Humanos del Pueblo de Oaxaca",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["951 503 02 20"],
    web: "https://www.derechoshumanosoaxaca.org/",
    addres:
      "Calle de los Derechos Humanos No. 210, Col. América, C.P. 68050, Oaxaca, Oaxaca",
  },
  {
    estado: "Oaxaca",
    name: "Grupo de estudios sobre la mujer Rosario Castellanos (GES Mujer)",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["951 516 6810"],
    web: "https://www.gesmujer.org/sitio/",
    addres:
      "Dirección:Tercera Privada de Guadalupe Victoria 107, Colonia Libertad. Oaxaca, Oaxaca.",
  },
  {
    estado: "Oaxaca",
    name: "Secretaría de las Mujeres de Oaxaca",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["(951)2072836"],
    web: "https://www.oaxaca.gob.mx/smo/unidad-paimef/",
    addres:
      "Heroica Escuela Naval Militar 221, Reforma, 68050 Oaxaca de Juárez, Oax.",
  },
  {
    estado: "Puebla",
    name: "Comisión de Derechos Humanos del Estado de Puebla",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, atención a quejas",
    phones: ["222 309 4700, Lada sin costo 800 201 01 05"],
    web: "https://www.cdhpuebla.org.mx/v1/",
    addres: "5 poniente #339 Col. Centro, C.P. 72000, Puebla, Puebla",
  },
  {
    estado: "Puebla",
    name: "Fundación Juconi",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención psicológica",
    phones: ["222 237 9416"],
    web: "https://www.juconi.org.mx/",
    addres: "Privada Volcán de Colima No. 2720, Volcanes, Puebla, Puebla",
  },
  {
    estado: "Puebla",
    name: "Secretaría de Igualdad Sustantiva de Puebla",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["22 23 03 48 00 Ext. 3227 y 3228"],
    web: "http://sis.puebla.gob.mx/",
    addres: "Av. 2 Sur, No. 902, Col. Centro, Puebla, C.P. 72000",
  },
  {
    estado: "Puebla",
    name: "Red de Abogadas Feministas de Puebla",
    tipo: "Red",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal ",
    phones: ["222 579 9672"],
    web: "https://www.facebook.com/AbogadasFeministasPueblaTlaxcala/",
  },
  {
    estado: "Querétaro",
    name: "CLEIDH, Colectivo de Litigio Estratégico e Investigación en Derechos Humanos",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias",
    phones: ["442-453-8270 y 442-831-9212"],
    web: "https://www.facebook.com/colectivoleidh/",
    addres: "N/D",
  },
  {
    estado: "Querétaro",
    name: "Defensoría de Derechos Humanos de Querétaro",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: [
      "442 214 0837 y 442 214 6007, Lada gratuita 800 400 6800, Teléfono de guardia 442 109 5400",
    ],
    web: "https://ddhqro.org/",
    addres: "Hidalgo No. 6, Colonia Centro Histórico",
  },
  {
    estado: "Querétaro",
    name: "Instituto Queretano de la Mujer",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 008 3568 y 442 216 4757"],
    web: "http://www.institutoqueretanodelasmujeres.gob.mx/",
    addres: "Mariano Reyes No. 17, Col. Centro, Querétaro, Querétaro.",
  },
  {
    estado: "Quintana Roo",
    name: "Comisión de Derechos Humanos del Estado de Quintana Roo",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["983 832 70 90 y 983 832 70 90"],
    web: "http://www.derechoshumanosqroo.org.mx/portal/portal/",
    addres:
      "Adolfo López Mateos No. 424, esq. Nápoles, Col Campestre, C.P. 77030, Chetumal, Quintana Roo",
  },
  {
    estado: "Quintana Roo",
    name: "Eleonora Mendoza A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["984 179 3354"],
    web: "https://rutasparafortalecer.org/osc/eleonora-mendoza-a-c/",
    addres:
      "Calle Mirlo Pardo No. 25, lote 4, manzana 26, Fraccionamiento Villas del Sol, Playa del Carmen, Quintan Roo",
  },
  {
    estado: "Quintana Roo",
    name: "Instituto Quintanarroense de la Mujer - PAIMEF",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["983 833 1323"],
    web: "https://qroo.gob.mx/iqm",
    addres: "Av. Juárez 49, Centro, C.P 77000, Chetumal, Quintana Roo.",
  },
  {
    estado: "San Luis Potosí",
    name: "Comisión Estatal de Derechos Humanos de San Luis Potosí",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["Lada sin costo 800 2639 955"],
    web: "http://www.cedhslp.org.mx/web2",
    addres:
      "Mariano Otero Nº 685, Col. Tequisquiapan, San Luis Potosí, S.L.P. C.P. 78250",
  },
  {
    estado: "San Luis Potosí",
    name: "Instituto de las Mujeres del Estado de San Luis Potosí",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 672 1433"],
    web: "https://slp.gob.mx/imes/Paginas/Inicio.aspx",
    addres: "Madero No. 305, Zona Centro, C.P. 78000",
  },
  {
    estado: "San Luis Potosí",
    name: "Otra Oportunidad A.C",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, atención médica, canalización a refugios",
    phones: ["444 814 7231"],
    web: "http://www.otraoportunidad.altervista.org/quienes_somos.html",
    addres:
      "3a. Privada de Francisco Javier Mina N° 210 Centro San Luis PotosíSan Luis Potosí 78000",
  },
  {
    estado: "Sinaloa",
    name: "Comisión Estatal de los Derechos Humanos de Sinaloa",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["667 752 2421 y 667 752 2575"],
    web: "https://www.cedhsinaloa.org.mx/",
    addres:
      "Ruperto L. Paliza No. 566 Sur, esquina con Ignacio Ramírez Colonia Miguel Alemán, C.P. 80200, Culiacán, Sinaloa",
  },
  {
    estado: "Sinaloa",
    name: "Instituto Sinaloense de las Mujeres",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 966 3866"],
    web: "https://ismujeres.gob.mx/",
    addres: "Álvaro Obregón No. 1265 sur, Col Guadalupe, C.P. 80220",
  },
  {
    estado: "Sonora",
    name: "Comisión Estatal de Derechos Humanos de Sonora",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["Lada sin costo 800 627 2800"],
    web: "https://www.cedhsonora.org.mx/Pagina/public/",
    addres: "Blvd. Luis Encinas y Periférico Poniente, Hermosillo Sonora",
  },
  {
    estado: "Sonora",
    name: "Instituto Sonorense de la Mujer",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["662 217 4986"],
    web: "https://ism.sonora.gob.mx/",
    addres:
      "Centro de Gobierno, Edif. Sonora, 3er nivel, Ala Norte, Blvd. Paseo Río Sonora Comonfort, Col. Villa de Seris",
  },
  {
    estado: "Tabasco",
    name: "Comisión Estatal de los Derechos Humanos de Tabasco",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: [
      "993 315 35 45 – 993 315 34 67, Número de guardia 9934 36 4437, Lada sin costo 800 000 23 34",
    ],
    web: "http://www.cedhtabasco.org.mx/",
    addres:
      "Boulevard Adolfo Ruiz Cortines, esquina Prolongación Francisco J. Mina #503Col. Casa Blanca, Villahermosa, Tabasco, México.CP:86060",
  },
  {
    estado: "Tabasco",
    name: "Instituto Estatal de las Mujeres de Tabasco",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["993 316 6488 ext. 102"],
    web: "https://tabasco.gob.mx/iem",
    addres:
      "Calle Antonio Suárez Hernández Núm. 136, col. reforma, c.p. 86035, col. Villa Hermosa",
  },
  {
    estado: "Tabasco",
    name: "LUNAS Libres y Unidas en Nuevas Acciones Sororales A.C",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["933 110 6555"],
    web: "https://www.facebook.com/pages/category/Local-Business/LUNAS-AC-248171936126352/",
    addres:
      "Calle Sor Juana Inés de la Cruz, Colonia Centro, Comalcalco, Tabasco",
  },
  {
    estado: "Tamaulipas",
    name: "Comisión de Derechos Humanos del Estado de Tamaulipas",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal",
    phones: ["834 312 4612"],
    web: "http://codhet.org.mx/",
    addres: "Río Guayalejo 223, Zozaya, 87070 Cd Victoria, Tamaulipas",
  },
  {
    estado: "Tamaulipas",
    name: "Instituto de las Mujeres en Tamaulipas",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["834 110 1449 y 834 110 1500"],
    web: "https://www.tamaulipas.gob.mx/mujeres/",
    addres:
      "Ex fábrica textil de San Manuel S/N, Pueblo de San Miguel Contla, Mpio, de Santa Cruz, Tlax. C.P. 70093.",
  },
  {
    estado: "Tlaxcala",
    name: "Comisión Estatal de Derechos Humanos de Tlaxcala",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas y Asesoría Jurídica",
    phones: [
      "246 46 21630, 246 46 29160, 246 46 27595, 246 46 25184 Lada sin costo: 01800 337 48 62",
    ],
    web: "http://cedhtlaxcala.cedhtlax.org.mx/index.php?option=com_content&amp;view=article&amp;id=1:bienvenidos&amp;catid=29:the-cms",
    addres:
      "Av. Arquitectos No. 27 Col. Loma Bonita C.P. 90090 Tlaxcala, Tlaxcala",
  },
  {
    estado: "Tlaxcala",
    name: "Instituto Estatal de la Mujer de Tlaxcala",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 838 7073"],
    web: "https://mujer.tlaxcala.gob.mx/index.php/atenciones",
    addres:
      "Ex Fábrica de San Manuel s/n, Barrio Nuevo, San Miguel Contla, Santa Cruz Tlaxcala.",
  },
  {
    estado: "Veracruz",
    name: "Centro de Derechos Humanos de los Pueblos del Sur de Veracruz “BETY CARIÑO” A.C.",
    tipo: "Sociedad Civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["N/D"],
    web: "http://cdhbetycarino.blogspot.com/",
    addres:
      "Zaragoza s/n, Barrio Tercero, C.P. 95940, Tatahuicalpan de Juárez, Veracruz",
  },
  {
    estado: "Veracruz",
    name: "Comisión Estatal de Derechos Humanos de Veracruz",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal y atención a quejas",
    phones: ["228 141 4300, Lada sin costo 800 260 2200"],
    web: "http://www.cedhveracruz.org.mx/cedhv/",
    addres:
      "Pico de Orizaba No. 5 Colonia, Sipeh Animas, 91067, Xalapa-Enríquez, Ver.",
  },
  {
    estado: "Veracruz",
    name: "Instituto Veracruzano de las Mujeres",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 906 8537"],
    web: "http://www.ivermujeres.gob.mx/",
    addres:
      "Av. Adolfo Ruiz Cortines #1618 Francisco Ferrer Guardia C.P. 91020",
  },
  {
    estado: "Yucatán",
    name: "Comisión de Derechos Humanos del Estado de Yucatán",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: [
      "999 927 8596, 999 927 2201, 999 927 9275, Lada sin costo 800 226 3439",
    ],
    web: "https://www.codhey.org/?fbclid=IwAR2IEJBjWMJ3s7o-W42CSjfrhsgEp36ULRSG0ZLBHaybBqZfd0c4Jkps2ak",
    addres:
      "Calle 20 No. 391 A x 31-D y 31-F, Col. Nueva Alemán. C.P. 97146, Mérida, Yucatán",
  },
  {
    estado: "Yucatán",
    name: "Secretaría de las Mujeres de Yucatán",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 667 7787 y 999 925 0543"],
    web: "https://tramites.yucatan.gob.mx/semujeres",
    addres:
      "Calle 86 No. 499 «C» altos, Ex penitenciaría Juárez, Centro, Mérida, Yucatán, C.P. 97000.",
  },
  {
    estado: "Yucatán",
    name: "Unidad de Atención Sicológica, Sexológica y Educativa para el Crecimiento Personal, A.C. (UNASSE)",
    tipo: "Sociedad civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["00 52 1 999 667 066 y Whatsapp 00 52 1 999 321 7541"],
    web: "https://unasse.org/",
    addres: "Calle 81 No. 486 A X 56 y 58, Centro, CP. 97000 Mérida, Yuc.",
  },
  {
    estado: "Yucatán",
    name: "APIS Sureste, Fundación para la Equidad, A.C.",
    tipo: "Sociedad civil",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica, refugio",
    phones: ["9999 88 40 48"],
    web: "https://apisfundacion.com/serviciosdeatencion/",
  },
  {
    estado: "Zacatecas",
    name: "Comisión Estatal de Derechos Humanos de Zacatecas",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Atención a quejas",
    phones: ["Celular de guardia 492 124 7730, Lada sin costo 800 624 2727"],
    web: "https://cdhezac.org.mx/",
    addres:
      "Av. Jesús Reyes Heroles No. 204-2, Col. Javier Barros Sierra, C.P. 98090, Zacatecas, Zacatecas",
  },
  {
    estado: "Zacatecas",
    name: "Secretaría de las Mujeres para el Estado de Zacatecas",
    tipo: "Organismo gubernamental",
    tags: "refugio, asesoría legal, atención a quejas, atención psicológica, interrupción legal del embarazo, atención médica, atienden infancias, Asesoría legal, atención psicológica",
    phones: ["800 830 0308"],
    web: "https://semujer.zacatecas.gob.mx/direccion-de-los-centros-de-atencion/#1558643027634-eb2aa0f8-b1cb",
    addres:
      "Circuito Cerro del Gato, Edificio K, Piso 1, Col. Ciudad Administrativa, C.P. 98160, Zacatecas, Zacatecas. ",
  },
]
